### ISSUE TITLE
Exception while running local test on Windows

### ISSUE THREAD

**Issue by ckzgraphics** [browserstack/nightwatch-browserstack#27]
**Error-**

{{ Connecting local
C:\Users\<User>\Documents\nightwatch-browserstack\scripts\local.runner.js:14
if (error) throw error;
^
LocalError
at C:\Users\<User>\Documents\nightwatch-browserstack\node_modules\browserstack-local\lib\Local.js:58:20
at ChildProcess.exithandler (child_process.js:280:7)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:962:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5 }}

**Steps to reproduce-**

1. Clone the git repo- https://github.com/browserstack/nightwatch-browserstack
2. Complete the steps mentioned in the [README.md](https://github.com/browserstack/nightwatch-browserstack/blob/master/README.md) file
3. Execute the command- _npm run local_

**System Details-** Windows 10

**Comment by JohnamLane** [comment]
I had this same issue. On line 14 of local.runner.js, the BROWSERSTACK_ACCESS_KEY is pulled from .env
This assumes you are pulling this secret from a local .env file.

I fixed this by adding the dotenv NPM package to my package.json, then adding the following to the top of local.runner.js:
`require('dotenv').config();`

From there, make sure you have a .env in your project with the following in it:
`BROWSERSTACK_ACCESS_KEY=<Your Key>`

**Comment by vedharish** [comment]
@ckzgraphics Can you share local.log file generated in the working directory from the code? [Check](https://github.com/browserstack/browserstack-local-nodejs/blob/230ec9357c95950c27dc5221324213a7525ec10d/lib/Local.js#L14)
