### ISSUE TITLE
Errors when running parallel_local or local configurations 

### ISSUE THREAD

**Issue by ligarcia10** [browserstack/nightwatch-browserstack#32]
nightwatch-browserstack>npm run local

> nightwatch-browserstack@0.1.1 local D:\repos\github\nightwatch-browserstack
> node scripts/local.runner.js -c conf/local.conf.js

Connecting local

D:\repos\github\nightwatch-browserstack\scripts\local.runner.js:14
    if (error) throw error;
               ^
LocalError
    at D:\repos\github\nightwatch-browserstack\node_modules\browserstack-local\lib\Local.js:58:20
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-browserstack@0.1.1 local: `node scripts/local.runner.js -c conf/local.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch-browserstack@0.1.1 local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

nightwatch-browserstack>npm run parallel_local

> nightwatch-browserstack@0.1.1 parallel_local D:\repos\github\nightwatch-browserstack
> node scripts/local.runner.js -c conf/parallel_local.conf.js -e chrome,firefox,safari

Connecting local

D:\repos\github\nightwatch-browserstack\scripts\local.runner.js:14
    if (error) throw error;
               ^
LocalError
    at D:\repos\github\nightwatch-browserstack\node_modules\browserstack-local\lib\Local.js:58:20
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nightwatch-browserstack@0.1.1 parallel_local: `node scripts/local.runner.js -c conf/parallel_local.conf.js -e chrome,firefox,safari`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nightwatch-browserstack@0.1.1 parallel_local script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by shawnlobo96** [comment]
Hey @ligarcia10,

The error you received was since the local testing binary did not start. This could happen if you are behind a proxy and the local testing binary was unable to connect to Browserstack's infrastructure.

Check with your network team if traffic to *.browserstack.com is whitelisted on ports 80 and 443 and WebSocket traffic is allowed to pass through?

Can you also manually run the binary on your machine and share the console output?

1) Download the binary
[OS X (10.7 and above)
](https://www.browserstack.com/browserstack-local/BrowserStackLocal-darwin-x64.zip)[Linux 32-bit](https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-ia32.zip)
[Linux 64-bit](https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip)
[Windows (XP and above)](https://www.browserstack.com/browserstack-local/BrowserStackLocal-win32.zip)

2) Run it in the terminal/cmd prompt
Mac OS/ Linux:
`./BrowserStackLocal --key <BROWSERSTACK_ACCESS_KEY>`
Windows:
`BrowserStackLocal.exe --key <BROWSERSTACK_ACCESS_KEY>`
